import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Airplay,
  AlarmClock,
  Apple,
  Award,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Brain,
  Calendar,
  Camera,
  CheckCircle,
  Clock,
  Cloud,
  Compass,
  Cpu,
  Droplets,
  Dumbbell,
  Eye,
  Feather,
  Flame,
  Flower2,
  Globe,
  Heart,
  HeartPulse,
  Home,
  Leaf,
  Lightbulb,
  MapPin,
  Moon,
  Mountain,
  Music,
  PartyPopper,
  PawPrint,
  PenLine,
  PlayCircle,
  ShieldCheck,
  Sparkles,
  Star,
  Sunrise,
  Sunset,
  Sun,
  Target,
  TreePine,
  Umbrella,
  Users,
  Waves,
  Wind,
  Zap,
} from "lucide-react";

export type CategoryIconOption = {
  name: string;
  label: string;
  Icon: LucideIcon;
};

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [
  { name: "Activity", label: "Activity", Icon: Activity },
  { name: "Airplay", label: "Airplay", Icon: Airplay },
  { name: "AlarmClock", label: "Alarm clock", Icon: AlarmClock },
  { name: "Apple", label: "Apple", Icon: Apple },
  { name: "Award", label: "Award", Icon: Award },
  { name: "Bell", label: "Bell", Icon: Bell },
  { name: "BookOpen", label: "Book open", Icon: BookOpen },
  { name: "Book", label: "Book", Icon: Book },
  { name: "Bookmark", label: "Bookmark", Icon: Bookmark },
  { name: "Brain", label: "Brain", Icon: Brain },
  { name: "Calendar", label: "Calendar", Icon: Calendar },
  { name: "Camera", label: "Camera", Icon: Camera },
  { name: "CheckCircle", label: "Check circle", Icon: CheckCircle },
  { name: "Clock", label: "Clock", Icon: Clock },
  { name: "Cloud", label: "Cloud", Icon: Cloud },
  { name: "Compass", label: "Compass", Icon: Compass },
  { name: "Cpu", label: "CPU", Icon: Cpu },
  { name: "Droplets", label: "Droplets", Icon: Droplets },
  { name: "Dumbbell", label: "Dumbbell", Icon: Dumbbell },
  { name: "Eye", label: "Eye", Icon: Eye },
  { name: "Feather", label: "Feather", Icon: Feather },
  { name: "Flame", label: "Flame", Icon: Flame },
  { name: "Flower2", label: "Flower", Icon: Flower2 },
  { name: "Globe", label: "Globe", Icon: Globe },
  { name: "Heart", label: "Heart", Icon: Heart },
  { name: "HeartPulse", label: "Heart pulse", Icon: HeartPulse },
  { name: "Home", label: "Home", Icon: Home },
  { name: "Leaf", label: "Leaf", Icon: Leaf },
  { name: "Lightbulb", label: "Lightbulb", Icon: Lightbulb },
  { name: "MapPin", label: "Map pin", Icon: MapPin },
  { name: "Moon", label: "Moon", Icon: Moon },
  { name: "Mountain", label: "Mountain", Icon: Mountain },
  { name: "Music", label: "Music", Icon: Music },
  { name: "PartyPopper", label: "Party popper", Icon: PartyPopper },
  { name: "PawPrint", label: "Paw print", Icon: PawPrint },
  { name: "PenLine", label: "Pen", Icon: PenLine },
  { name: "PlayCircle", label: "Play circle", Icon: PlayCircle },
  { name: "ShieldCheck", label: "Shield check", Icon: ShieldCheck },
  { name: "Sparkles", label: "Sparkles", Icon: Sparkles },
  { name: "Star", label: "Star", Icon: Star },
  { name: "Sunrise", label: "Sunrise", Icon: Sunrise },
  { name: "Sunset", label: "Sunset", Icon: Sunset },
  { name: "Sun", label: "Sun", Icon: Sun },
  { name: "Target", label: "Target", Icon: Target },
  { name: "TreePine", label: "Tree pine", Icon: TreePine },
  { name: "Umbrella", label: "Umbrella", Icon: Umbrella },
  { name: "Users", label: "Users", Icon: Users },
  { name: "Waves", label: "Waves", Icon: Waves },
  { name: "Wind", label: "Wind", Icon: Wind },
  { name: "Zap", label: "Zap", Icon: Zap },
];

export const CATEGORY_ICON_MAP = CATEGORY_ICON_OPTIONS.reduce<Record<string, LucideIcon>>(
  (acc, item) => {
    acc[item.name] = item.Icon;
    return acc;
  },
  {}
);
